### ISSUE TITLE
0.3 barely works

### ISSUE THREAD

**Issue by microcreators** [Pamblam/td#1]
hi. so how do i help making it work properly? issues facing in the 0.3 version from mozilla site:
- none of the request values can be edited, which is the whole point here
- post requests bring the dialog window twice for me and eventually the site hangs, not processing the request at all
thanks

edit: ok... looks like it's work in progress on mozilla side. requested like year ago.

**Comment by Pamblam** [comment]
It works exactly as expected.

the new APIs only allow header changes on "beforeHeadersSent" while postdata can only be viewed on "onRequestSent" - hence the two dialogues. 

changing requestbody data is not currently supported by the API. 

I'll add some code to make this clearer, maybe today.
