### ISSUE TITLE
Upgrade to android pie

### ISSUE THREAD

**Issue by ghost** [Pamblam/td#12]
Not working on pie

**Comment by fluks** [comment]
I don't think this has ever worked on any version of Android? [Windows APIs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs#windows) aren't supported on Android. Requests and headers are shown in a new window on PC, it would need to be implemented in some other manner, probably in a new tab.

Maybe Pamblam just left the android checkbox checked on AMO accidentally. I think it defaulted to enabling both mobile and PC versions on AMO, I'm not sure.

**Comment by Pamblam** [comment]
This needs to be rebuilt and re-submitted to Mozilla anyway since recent changes have been made. Thing is, I can't figure out where to disable Android in the Mozilla developers page for this add on.

**Comment by fluks** [comment]
My Add-Ons -> choose the add-on -> Manage Status & Versions on the left -> choose version -> then click the x on Firefox for Android to remove it. It's not there?

**Comment by Pamblam** [comment]
Disabled Android on AMO and submitted the latest updates as well.
