### ISSUE TITLE
Clean up the interface

### ISSUE THREAD

**Issue by Pamblam** [Pamblam/td#2]
The HTML/CSS interface could be a lot nicer and more consistent. 

In the /popups folder there are 3 folder, each contains an HTML file. These are what need to be cleaned up.

I'll leave this here as a Hacktoberfest issue in case anyone is interested in an Easy PR.

**Comment by carolinajimenez26** [comment]
I'll do it

**Comment by Pamblam** [comment]
@carolinajimenez26 SWEET. Go for it.
